### ISSUE TITLE
Using Django 1.11, "context must be a dict rather than RequestContext."

### ISSUE THREAD

**Issue by philgyford** [jazzband/django-flatblocks#19]
Having upgraded to Django 1.11.0, when I use a flatblock in a template I get `context must be a dict rather than RequestContext.`

```Traceback (most recent call last):
  File "/Users/phil/.pyenv/versions/django-hines/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/phil/.pyenv/versions/django-hines/lib/python3.6/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/phil/.pyenv/versions/django-hines/lib/python3.6/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/Users/phil/.pyenv/versions/django-hines/lib/python3.6/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/Users/phil/.pyenv/versions/django-hines/lib/python3.6/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/Users/phil/.pyenv/versions/django-hines/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Users/phil/.pyenv/versions/django-hines/lib/python3.6/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Users/phil/.pyenv/versions/django-hines/lib/python3.6/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/phil/.pyenv/versions/django-hines/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/phil/.pyenv/versions/django-hines/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/phil/.pyenv/versions/django-hines/lib/python3.6/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/Users/phil/.pyenv/versions/django-hines/lib/python3.6/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/Users/phil/.pyenv/versions/django-hines/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/phil/.pyenv/versions/django-hines/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/phil/.pyenv/versions/django-hines/lib/python3.6/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/Users/phil/.pyenv/versions/django-hines/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/phil/.pyenv/versions/django-hines/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/phil/.pyenv/versions/django-hines/lib/python3.6/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/Users/phil/.pyenv/versions/django-hines/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/phil/.pyenv/versions/django-hines/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/phil/.pyenv/versions/django-hines/lib/python3.6/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/Users/phil/.pyenv/versions/django-hines/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/phil/.pyenv/versions/django-hines/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/phil/.pyenv/versions/django-hines/lib/python3.6/site-packages/django/template/library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/Users/phil/.pyenv/versions/django-hines/lib/python3.6/site-packages/flatblocks/templatetags/flatblocks.py", line 92, in flatblock
    result = render_to_string(using, context)
  File "/Users/phil/.pyenv/versions/django-hines/lib/python3.6/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Users/phil/.pyenv/versions/django-hines/lib/python3.6/site-packages/django/template/backends/django.py", line 64, in render
    context = make_context(context, request, autoescape=self.backend.engine.autoescape)
  File "/Users/phil/.pyenv/versions/django-hines/lib/python3.6/site-packages/django/template/context.py", line 287, in make_context
    raise TypeError('context must be a dict rather than %s.' % context.__class__.__name__)
TypeError: context must be a dict rather than RequestContext.
```

(I assume this is the currently authoritative django-flatblocks repo... it was a bit of a circuitous route to get here.)

**Comment by funkybob** [comment]
This likely started earlier, or at least would have flagged warnings when pluggable template engines was added.

Yes, this is the authoritative repo. The original was ceded to me, and I handed it over to JazzBand as I had no time, and nobody appeared to be using it.

**Comment by funkybob** [comment]
Try this and see if it helps:

```
diff --git a/flatblocks/templatetags/flatblocks.py b/flatblocks/templatetags/flatblocks.py
index 227c846..a4ebe80 100644
--- a/flatblocks/templatetags/flatblocks.py
+++ b/flatblocks/templatetags/flatblocks.py
@@ -88,8 +88,9 @@ def flatblock(context, slug, evaluated=False,
         flatblock.header = template.Template(flatblock.header).render(context)
 
     if using:
-        with context.push(flatblock=flatblock):
-            result = render_to_string(using, context)
+        ctx = context.flatten()
+        ctx['flatblock'] = flatblock
+        result = render_to_string(using, ctx)
     else:
         result = flatblock.content
```
