### ISSUE TITLE
Release for Django 3 compatibility

### ISSUE THREAD

**Issue by craiga** [jazzband/django-flatblocks#28]
Any chance of a new release for Django 3 compatibility?

Running migrations with Django 3 and the latest version on PyPi gives me the following error (I assume this has to do with dropped Python 2 support), but installing directly from git seems to work fine.

```
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "…/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "…/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "…/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "…/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "…/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "…/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "…/flatblocks/models.py", line 3, in <module>
    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' (…/django/utils/encoding.py)
```

**Comment by martey** [comment]
This should be resolved by 1.0.0 (see #39).
