### ISSUE TITLE
Pip install fails from master

### ISSUE THREAD

**Issue by digicase** [jazzband/django-flatblocks#33]
I can no longer install django flatblocks due to an error during pip install.

The pip install command used was `-e git+git://github.com/jazzband/django-flatblocks.git@master#egg=django-flatblocks`

I'm installing from a github URL as I need the latest updates, for compatibility with Django 2. I have pinned the requirement now to an older commit to get it working `-e git+git://github.com/jazzband/django-flatblocks.git@41a037959f05ad666ee9a1645db1907c81e4bd78#egg=django-flatblocks`.

```
ERROR: Command errored out with exit status 1:
     command: /Users/xxxxxx/.virtualenvs/eb-3-dev/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/xxxxxx/.virtualenvs/eb-3-dev/src/django-flatblocks/setup.py'"'"'; __file__='"'"'/Users/xxxxxx/.virtualenvs/eb-3-dev/src/django-flatblocks/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/ph/3jc2sm6d611c76mjzj8crfj80000gn/T/pip-pip-egg-info-t312zlun
         cwd: /Users/xxxxxx/.virtualenvs/eb-3-dev/src/django-flatblocks/
    Complete output (34 lines):
    WARNING: The wheel package is not available.
    /Users/xxxxxx/.virtualenvs/eb-3-dev/src/django-flatblocks/.eggs/setuptools_scm-5.0.1-py3.7.egg/setuptools_scm/version.py:88: UserWarning: tag 'release/0.9.4' no version found
      warnings.warn("tag {!r} no version found".format(tag))
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/xxxxxx/.virtualenvs/eb-3-dev/src/django-flatblocks/setup.py", line 50, in <module>
        "Django (>=2.2)",
      File "/Users/xxxxxx/.virtualenvs/eb-3-dev/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/Users/xxxxxx/.pyenv/versions/3.7.9/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/xxxxxx/.virtualenvs/eb-3-dev/lib/python3.7/site-packages/setuptools/dist.py", line 426, in __init__
        k: v for k, v in attrs.items()
      File "/Users/xxxxxx/.pyenv/versions/3.7.9/lib/python3.7/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/Users/xxxxxx/.virtualenvs/eb-3-dev/lib/python3.7/site-packages/setuptools/dist.py", line 717, in finalize_options
        ep(self)
      File "/Users/xxxxxx/.virtualenvs/eb-3-dev/lib/python3.7/site-packages/setuptools/dist.py", line 724, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/Users/xxxxxx/.virtualenvs/eb-3-dev/src/django-flatblocks/.eggs/setuptools_scm-5.0.1-py3.7.egg/setuptools_scm/integration.py", line 26, in version_keyword
        dist.metadata.version = _get_version(config)
      File "/Users/xxxxxx/.virtualenvs/eb-3-dev/src/django-flatblocks/.eggs/setuptools_scm-5.0.1-py3.7.egg/setuptools_scm/__init__.py", line 173, in _get_version
        parsed_version = _do_parse(config)
      File "/Users/xxxxxx/.virtualenvs/eb-3-dev/src/django-flatblocks/.eggs/setuptools_scm-5.0.1-py3.7.egg/setuptools_scm/__init__.py", line 127, in _do_parse
        version = _version_from_entrypoints(config) or _version_from_entrypoints(
      File "/Users/xxxxxx/.virtualenvs/eb-3-dev/src/django-flatblocks/.eggs/setuptools_scm-5.0.1-py3.7.egg/setuptools_scm/__init__.py", line 65, in _version_from_entrypoints
        version = _call_entrypoint_fn(root, config, ep.load())
      File "/Users/xxxxxx/.virtualenvs/eb-3-dev/src/django-flatblocks/.eggs/setuptools_scm-5.0.1-py3.7.egg/setuptools_scm/__init__.py", line 46, in _call_entrypoint_fn
        return fn(root, config=config)
      File "/Users/xxxxxx/.virtualenvs/eb-3-dev/src/django-flatblocks/.eggs/setuptools_scm-5.0.1-py3.7.egg/setuptools_scm/git.py", line 139, in parse
        branch=branch,
      File "/Users/xxxxxx/.virtualenvs/eb-3-dev/src/django-flatblocks/.eggs/setuptools_scm-5.0.1-py3.7.egg/setuptools_scm/version.py", line 212, in meta
        assert parsed_version is not None, "Can't parse version %s" % tag
    AssertionError: Can't parse version release/0.9.4
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by martey** [comment]
Could this be related to https://github.com/pypa/pip/issues/7554? Does this error disappear if you use a "git+https" URL instead?

**Comment by digicase** [comment]
Using `-e git+https://github.com/jazzband/django-flatblocks.git@master#egg=django-flatblocks` does work. Thanks @martey
